### ISSUE TITLE
Inability to log back in to test flight after log out

### ISSUE THREAD

**Issue by ats114** [StanfordBDHG/ENGAGE-HF-iOS#18]
### Description

I logged out of test flight and then tried to log back in. It doesnt let you click the continue to log back in 

### Reproduction

Log out of account and then try to log back in

### Expected behavior

Would be expected to be able to click the name below and log back in but the name is not click able
![Screenshot 2024-06-11 at 10 36 53 AM](https://github.com/StanfordBDHG/ENGAGE-HF-iOS/assets/68678339/eb1c6535-e217-4b12-932e-c58d34b13081)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by Supereg** [comment]
Thank you for reporting this issue. Could reproduce the issue thanks to the steps you provided.

After logging back in, you can force quit the app to restore functionality. Use this as a workaround till the issue is fixed.

**Comment by Supereg** [comment]
The issue was resolved and an updated TestFlight build is available.
