### ISSUE TITLE
Disable Account Deletion

### ISSUE THREAD

**Issue by nriedman** [StanfordBDHG/ENGAGE-HF-iOS#44]
### Problem

Currently, account deletion seems to be handled internally by SpeziAccounts. However, we would prefer for the clinician/study team to handle account deletion instead of the patient.

### Solution

Disable account deletion as something that's possible to do in the app, or throw an error referring the patient to their clinician. Either way, until this is solved, I went ahead and removed the code in the Onboarding UI tests that tests the deletion functionality

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by vishnuravi** [comment]
Thanks @nriedman. To comply with App Store Guidelines, there must be a method for [account deletion], which can be a link to the study website or other method to contact the study team.
