### ISSUE TITLE
Restructure UI Tests to rely on Firestore Seeding

### ISSUE THREAD

**Issue by nriedman** [StanfordBDHG/ENGAGE-HF-iOS#59]
### Problem

@pauljohanneskraft recently merged seeding functionality into StanfordBDHG/ENGAGE-HF-Firebase that will allow us to fill the emulators with mock data. However, our CI build currently does not use the StanfordBDHG/ENGAGE-HF-Firebase emulator. This is a blocking issue for testing views such as Education that rely on static data from the seeding function.

### Solution

Restructure the build-and-test job to clone the main branch of StanfordBDHG/ENGAGE-HF-Firebase, then start the emulator using the seeding function as described in the StanfordBDHG/ENGAGE-HF-Firebase documentation. Then, refactor the existing UI Tests to be compatible with the new emulator. Finally, write Unit Tests for the Education section targeting VideoManager / decoding videos from Firestore.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by Supereg** [comment]
To ensure UI test continue to work on the local machine, I would suggest to include the Firebase repo as a git submodule and update the checkout action to clone submodules. This might be an easy change in our. Build action hosted in the global .github repository.

**Comment by nriedman** [comment]
That sounds great @Supereg. @pauljohanneskraft had started with a slightly different approach in #24, but after discussing with him I think I'll go with the submodule route -- it seems like this use case is pretty much exactly what that's for!
