### ISSUE TITLE
Only show consent in onboarding if no consent.pdf is in the user's storage.

### ISSUE THREAD

**Issue by nriedman** [StanfordBDHG/ENGAGE-HF-iOS#72]
### Problem

Right now, we always show consent as part of the onboarding flow, even if the patient has already completed it (e.g. if they delete and re-download the app).

### Solution

Before displaying the consent view, we should check in Firebase Storage for a consent.pdf file, and if there is one then we skip this step of onboarding.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by vishnuravi** [comment]
This is a good idea. We do this in the [LifeSpace](https://github.com/StanfordBDHG/LifeSpace/blob/d2feb98edadb736462909e30b91eb4d2ab8e4888/LifeSpace/Onboarding/Consent.swift#L157) project. It should likely be a part of the template application also.
