### ISSUE TITLE
Handle Education Video fetching failure with content unavailable view.

### ISSUE THREAD

**Issue by nriedman** [StanfordBDHG/ENGAGE-HF-iOS#84]
### Problem

Right now, if we fail to fetch the educational videos from firestore (for if there are no videos in firestore), we show an essentially empty view in the Education tab. Instead, we should show a `ContentUnavailableView`.

### Solution

Add an if statement that will either show the `VideoList` if the `VideoManager` is not empty, and a `ContentUnavailableView` otherwise. Within the `VideoList`, if a `videoCollection` is empty (i.e. the section has no videos), consider not showing the `VideoListSection`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PaulGoldschmidt** [comment]
I would take a look into this issue and possibly implement this along with issue #57, as I assume the solution to both issues should be nearly identical in their implementation of the `ContentUnavailableView` 🚀

**Comment by nriedman** [comment]
Great idea! Fyi handling empty content has already been taken care of in the Heart Health view in a previous PR (I meant to close #57), so Education is the main place where this will be necessary. Feel free to adjust/add empty content handling in other views if you notice any inconsistencies! 🚀
