### ISSUE TITLE
AccountSetupSheet is dismissed after entering invitation code but before signing up

### ISSUE THREAD

**Issue by pauljohanneskraft** [StanfordBDHG/ENGAGE-HF-iOS#85]
### Description

After logging out, the AccountSetupSheet is shown, but immediately dismissed after entering the invitation code, but before the user is able to sign up/create a new account.

### Reproduction

1. Somehow manage to get a properly logged in user account (e.g. by signing up with an invitation code after a clean install).
2. Sign out
3. Wait for Invitation Code popup (i.e. AccountSetupSheet)
4. Enter a valid invitation code
5. Press the "Redeem Invitation Code" button
6. See that the sheet dismisses before the user can do any further sign up. Further, the user account won't be fully set up yet, meaning that there is actually no data in the app and all actions will fail due to authentication issues.

### Expected behavior

The user should be able to sign up with an account, e.g. by entering an email address and a password. After that, the user should be logged in successfully.

### Additional context

This sheet seems to be triggered by the accountRequired view modifier. In the change listener of AccountRequiredModifier, the presentingSheet property is set to false when the user is signed in, even if the account is anonymous.

Maybe, we can have an additional closure in the AccountRequiredModifier to specify whether a signed in account fulfills all the requirements of an account (e.g. in this case being that the account needs to not be anonymous).

May also be a deeper issue in SpeziFirebase or SpeziAccount, so @Supereg may have additional insights.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by Supereg** [comment]
This should be resolved once #83 gets merged.

**Comment by pauljohanneskraft** [comment]
You are right, sorry for opening this issue, didn't know the PR already exists.

**Comment by Supereg** [comment]
> You are right, sorry for opening this issue, didn't know the PR already exists.

Thanks for effort for tracking down and creating the issue. 🚀
Feel free to keep it open till the PR is merged.
